### ISSUE TITLE
Failed to execute script 'main' due to unhandled exception

### ISSUE THREAD

**Issue by adnfj17236** [IamCOD3X/Kernel-Builder#2]
┌──(kali㉿kali)-[~/kernelbuilder]
└─$ ls
Kernel_Builder  kernel_source

┌──(kali㉿kali)-[~/kernelbuilder]
└─$ ./Kernel_Builder                                                                                                                                         
Traceback (most recent call last):
  File "main.py", line 1306, in <module>
  File "pyfiglet/__init__.py", line 65, in figlet_format
  File "pyfiglet/__init__.py", line 794, in __init__
  File "pyfiglet/__init__.py", line 801, in setFont
  File "pyfiglet/__init__.py", line 126, in __init__
  File "pyfiglet/__init__.py", line 147, in preloadFont
pyfiglet.FontNotFound: small
[741532] Failed to execute script 'main' due to unhandled exception!

**Comment by IamCOD3X** [comment]
Whenever I'll get some time, I'll update the binary package

**Comment by IamCOD3X** [comment]
Check the new realease 
https://github.com/IamCOD3X/Kernel-Builder/releases/tag/v0.3

also if you still face this issue.. 
try :
pip install pyfiglet

**Comment by ALTERRQ** [comment]
I have the same issue, and it's still don't work for me.
Even after i installed pyfiglet.

**Comment by ALTERRQ** [comment]
This command fixed it:

sudo wget http://www.figlet.org/fonts/small.flf -O /usr/share/figlet/small.flf
